#
# Makefile for the ali Remote Process Call driver (drivers/rpc/Makefile)
#


obj-$(CONFIG_RPC_ALI)           += alirpc.o

alirpc-y := ali_rpc.o  ali_rpc_hld_base.o ali_rpc_dev_init.o  ali_version.o

obj-$(CONFIG_RPC_HLD_DECV)  += decv/

obj-$(CONFIG_RPC_HLD_DIS)   += dis/

obj-$(CONFIG_RPC_HLD_DECA)  += deca/

obj-$(CONFIG_RPC_HLD_SND)   += snd/

obj-$(CONFIG_RPC_HLD_GMA)   += gma/

obj-$(CONFIG_RPC_PE)        += pe/

obj-$(CONFIG_RPC_SBM)        += sbm/

obj-$(CONFIG_RPC_HLD_VBI)   += vbi/

obj-$(CONFIG_RPC_HLD_SDEC)  += sdec/

obj-$(CONFIG_RPC_HLD_AVSYNC)  += avsync/

obj-$(CONFIG_RPC_IMAGE)       += image/

