#
# Makefile for the ali Remote Process Call pe driver(drivers/rpc/pe/Makefile)
#

obj-$(CONFIG_RPC_PE)         += ali_rpc_pe.o

ali_rpc_pe-y := ali_rpc_pe_cache.o ali_rpc_pe_image.o ali_rpc_pe_music.o ali_rpc_pe_video.o

