#ifndef __ALI_SDEC_COMMON_H
#define __ALI_SDEC_COMMON_H

#include "ali_basic_common.h"


#define SDEC_CALL						0x00010000

#define CALL_SDEC_START				(SDEC_CALL+1)
#define CALL_SDEC_STOP					(SDEC_CALL+2)
#define CALL_SDEC_PAUSE				(SDEC_CALL+3)
#define CALL_LIB_SUBT_ATTACH			(SDEC_CALL+4)
#define CALL_OSD_SUBT_ENTER			(SDEC_CALL+5)
#define CALL_OSD_SUBT_LEAVE			(SDEC_CALL+6)

#define CALL_LIB_ISDBT_CC_INIT		(SDEC_CALL + 7)
#define CALL_OSD_ISDBT_CC_ENTER		(SDEC_CALL + 8)
#define CALL_OSD_ISDBT_CC_LEASE		(SDEC_CALL + 9)
#define CALL_LIB_ISDBT_CC_ATTACH	(SDEC_CALL + 10)

#define CALL_ISDBT_CC_DEC_ATTACH	(SDEC_CALL + 11)
#define CALL_ISDBT_CC_DISPLAY_INIT	(SDEC_CALL + 12)
#define CALL_ISDBT_CC_GET_CUR_LANG_BY_PID (SDEC_CALL + 13)

#define CALL_SUBT_ATSC_SET_BUF			(SDEC_CALL + 14)
#define CALL_SUBT_ATSC_STREAM_IDENTIFY	(SDEC_CALL + 15)
#define CALL_SUBT_ATSC_CREATE_TASK		(SDEC_CALL + 16)
#define CALL_SUBT_ATSC_TERMINATE_TASK	(SDEC_CALL + 17)
#define CALL_SUBT_ATSC_CLEAN_UP			(SDEC_CALL + 18)
#define CALL_SUBT_ATSC_DEL_TIMER		(SDEC_CALL + 19)
#define CALL_SUBT_ATSC_SHOW_ONOFF		(SDEC_CALL + 20)
#define CALL_SUBT_ATSC_PARSE_CREATE_TASK		(SDEC_CALL + 21)
#define CALL_SUBT_ATSC_PARSE_TERMINATE_TASK	(SDEC_CALL + 22)

#endif //__DRIVERS_ALI_RPC_HLD_SDEC_H

